#!/bin/sh

# For some reason, I couldn't get this to work when just executing the command. It tries to add random single quotes.
# As a workaround I use the eval command.
command="mvn compile exec:java -Dexec.args=\"$@\""
eval $command
